name: Jon Fields
favicon: null
layout_spectrum: 0.15086179436184466
typography_spectrum: 0.8441530580166727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.007013140246272087
  lightness: 0.5104692948516458
  saturation: 0.731490061385557
  rhythmicContrast: 0.6496533565223217
purpose: []
